# fly.toml app configuration file generated for pruevagetserverslink on 2023-11-08T17:35:21-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pruevagetserverslink"
primary_region = "mad"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
